### ISSUE TITLE
NameError: global name 'username_value' is not defined

### ISSUE THREAD

**Issue by toeytan** [B1ood6od/pokemon-go#1]
Getting the following error with the updated version

`Traceback (most recent call last):
  File "pogo-generator.py", line 279, in <module>
    main()
  File "pogo-generator.py", line 274, in main
    process_mailbox(M)
  File "pogo-generator.py", line 118, in process_mailbox
    account_file.write("%s,%s,%s\n" % (username_value, password_value, email_value))
NameError: global name 'username_value' is not defined'

Would you be able to advise how to fix this?

**Comment by jamezroux** [comment]
My only thought is that you could have downloaded a previous version (somehow?) Though not sure how. I did upload a version at one point that had a line which output in that function, but the current one doesn't. So if downloading the current script doesn't work, I really have no clue.
